### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by segg21** [Enthri/iBox-2#8]
So, I know Windows XP capability. Is it possible to run Linux? Possibly Ubuntu? Or any relative redhat that is small in size? 

CentOS could even work.

**Comment by jaromaz** [comment]
I was able to run Linux Debian Woody and ttylinux (486) on non-jailbroken iPad Mini 2 and iPhone 6+. 
We urgently need network support to be able to drive through SSH, because the default iBox keyboard does not work with bluetooth keyboards.

regards :)

**Comment by segg21** [comment]
@jaromaz adding bluetooth support shouldn't be hard, alltho I don't know object-c. Sorry.

Anyways, thanks for the reply.
